#                                                                        #
# Default routes configuration for the OpenAgenda.Application package    #
#                                                                        #

-
  name: 'Show standard index'
  uriPattern: ''
  defaults:
    '@package':    'OpenAgenda.Application'
    '@controller': 'Standard'
    '@action':     'index'
    '@format':     'html'
-
  name: 'All actions: JSON'
  uriPattern: '{@controller}/{@action}.json'
  defaults:
    '@package':    'OpenAgenda.Application'
    '@format':     'json'
-
  name: 'Meeting: JSON'
  uriPattern: 'meeting/{meeting.__identity}/{@action}.json'
  defaults:
    '@package':    'OpenAgenda.Application'
    '@controller': 'Meeting'
    '@format':     'json'
  routeParts:
    meeting:
      objectType: 'OpenAgenda\Application\Domain\Model\Meeting'
-
  name: 'Task: JSON'
  uriPattern: 'task/{task.__identity}/{@action}.json'
  defaults:
    '@package':    'OpenAgenda.Application'
    '@controller': 'Task'
    '@format':     'json'
  routeParts:
    task:
      objectType: 'OpenAgenda\Application\Domain\Model\Task'
-
  name: 'Person: JSON'
  uriPattern: 'person/{person.__identity}/{@action}.json'
  defaults:
    '@package':    'OpenAgenda.Application'
    '@controller': 'Person'
    '@format':     'json'
  routeParts:
    person:
      objectType: 'TYPO3\Party\Domain\Model\Person'
-
  name: 'Template: HTML'
  uriPattern: 'template/{controller}/{action}.{format}'
  defaults:
    '@package':    'OpenAgenda.Application'
    '@controller': 'Template'
    '@action':     'get'
    '@format':     'html'
-
  name: 'Ping: JSON'
  uriPattern: 'ping'
  defaults:
    '@package':    'OpenAgenda.Application'
    '@controller': 'Standard'
    '@action':     'ping'
    '@format':     'json'
-
  name: 'Registration'
  uriPattern: 'registration/{account}/{@action}/{_time}-{_hash}'
  defaults:
    '@package':    'OpenAgenda.Application'
    '@controller': 'Authentication'
    '@format':     'html'
  routeParts:
    account:
      handler:    'OpenAgenda\Application\Routing\EntityHandler'
      options:
        objectType: '\TYPO3\Flow\Security\Account'
        processInvalid: true