#                                                                        #
# Default routes configuration for the OpenAgenda.Application package    #
#                                                                        #

-
  name: 'Show standard index'
  uriPattern: ''
  defaults:
    '@package':    'OpenAgenda.Application'
    '@controller': 'Standard'
    '@action':     'index'
    '@format':     'html'
-
  name: 'JSON list view'
  uriPattern: '{@controller}/list.json'
  defaults:
    '@package':    'OpenAgenda.Application'
    '@action':     'list'
    '@format':     'json'
-
  name: 'JSON show view meeting'
  uriPattern: '{@controller}/{meeting}/show.json'
  defaults:
    '@package':    'OpenAgenda.Application'
    '@action':     'show'
    '@format':     'json'
  routeParts:
    meeting:
      objectType: 'OpenAgenda\Application\Domain\Model\Meeting'
-
  name: 'JSON show view task'
  uriPattern: '{@controller}/{task}/show.json'
  defaults:
    '@package':    'OpenAgenda.Application'
    '@action':     'show'
    '@format':     'json'
  routeParts:
    meeting:
      objectType: 'OpenAgenda\Application\Domain\Model\Task'
