#                                                                        #
# Default routes configuration for the OpenAgenda.Application package    #
#                                                                        #

-
  name: 'Show standard index'
  uriPattern: ''
  defaults:
    '@package':    'OpenAgenda.Application'
    '@controller': 'Standard'
    '@action':     'index'
    '@format':     'html'
