TYPO3:
  Flow:
    configuration:
      compileConfigurationFiles: FALSE
    security:
      enable: TRUE
      authentication:
        authenticationStrategy: oneToken
        providers:
          DefaultProvider:
            provider: 'PersistedUsernamePasswordProvider'

OpenAgenda:
  Application:
    Authentication:
      defaultRole: 'OpenAgenda.Application:Listener'
      directory:
        mailIdentifier: 'mail'
      postLoginUri: '/'
      postLogoutUri: '/'
    Validation:
      ModelScopeValidator:
        OpenAgenda\Application\Framework\Model\Account:
          create:
            properties:
              username:
                validators:
                  NotEmpty: []
                  EmailAddress: []
              firstName:
                validators:
                  NotEmpty: []
                  StringLength:
                    minimum: 2
              lastName:
                validators:
                  NotEmpty: []
                  StringLength:
                    minimum: 2
              password:
                validators:
                  NotEmpty: []
                  StringLength:
                    minimum: 8
              passwordRepeat:
                validators:
                  NotEmpty: []
                  StringLength:
                    minimum: 8
                  OpenAgenda\Application\Validation\Validator\SameValidator:
                    propertyValue: '$password'
            entity:
              factoryCallback: 'TYPO3\Flow\Security\AccountFactory->createAccountWithPassword($username, "")'
              resultProperty: 'username'
              validators:
                UniqueEntity:
                  identityProperties: ['accountIdentifier']
    PropertyMapping:
      OpenAgenda\Application\Domain\Model\Task:
        create:
          'OpenAgenda.Application:MeetingManager':
            allow: '*'
            types: ['create']
        update:
          default:
            allow: ['status']
            types: ['modify']
          'OpenAgenda.Application:MeetingManager':
            allow: '*'
            types: ['modify']
    Messaging:
      deliver: 'immediately'
      sender:
        mail: 'openagenda@hof-university.de'
        name: 'OpenAgenda'